sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
language: java
jdk:
  - oraclejdk8
  - openjdk8
cache:
  directories:
  - .autoconf
  - $HOME/.m2
before_install:
  - source .travis/start_xvfb.sh
script:
  - mvn license:check
  - mvn formatter:validate
  - mvn cobertura:cobertura
after_success:
  - mvn coveralls:report
