sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
language: java
jdk:
  - oraclejdk8
  - openjdk8
script:
  - mvn license:check
after_success:
  - mvn clean cobertura:cobertura coveralls:report