version: "{build} ({branch})"

shallow_clone: true
clone_folder: C:\projects\semux

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - echo %PATH%
  - echo %M2_HOME%
  - mvn -X -v

build_script:
  - cd C:\projects\semux
  - mvn clean install -DskipTests

test_script:
  - mvn test